"""
report.py — generates a self-contained, printable HTML report from an
analysis result. The browser's own "Print to PDF" produces the PDF output
required by the spec without adding a heavy PDF-rendering dependency for V1.
"""
from __future__ import annotations

import html


def _esc(x) -> str:
    return html.escape(str(x)) if x is not None else "—"


def _findings_html(findings: list[dict]) -> str:
    if not findings:
        return "<p class='muted'>No findings above threshold were raised for this track.</p>"
    rows = []
    for f in findings:
        freq = f"{f['frequency_range'][0]:.0f}–{f['frequency_range'][1]:.0f} Hz" if f.get("frequency_range") else ""
        time_r = f"{f['time_range'][0]:.1f}s–{f['time_range'][1]:.1f}s" if f.get("time_range") else ""
        evidence = "".join(f"<li>{_esc(e)}</li>" for e in f.get("evidence", []))
        recs = "".join(f"<li>{_esc(r)}</li>" for r in f.get("recommendations", []))
        rows.append(f"""
        <div class="finding sev-{f['severity']}">
          <div class="finding-head">
            <span class="pill">{_esc(f['severity']).upper()}</span>
            <strong>{_esc(f['title'])}</strong>
            <span class="muted">Confidence {round(f['confidence']*100)}%</span>
          </div>
          <div class="muted small">{freq} {time_r}</div>
          <div class="finding-body">
            <div><span class="label">Evidence</span><ul>{evidence}</ul></div>
            <div><span class="label">Why it matters</span><p>{_esc(f['explanation'])}</p></div>
            <div><span class="label">Try</span><ul>{recs}</ul></div>
          </div>
        </div>""")
    return "".join(rows)


def _band_rows(bands: list[dict]) -> str:
    rows = []
    for b in bands:
        label = b.get("label") or f"{b['range_hz'][0]}-{b['range_hz'][1]}"
        rows.append(f"<tr><td>{label}</td><td>{b['energy_db']:.1f} dB</td><td>{b['relative_energy']*100:.1f}%</td></tr>")
    return "".join(rows)


def generate_report_html(result: dict) -> str:
    m = result["metadata"]
    lo = result["loudness"]
    dy = result["dynamics"]
    le = result["low_end"]
    kb = result["kick_bass"]
    st = result["stereo"]
    cl = result["clipping"]
    mh = result["mix_health"]
    genre = result["genre"]

    css = """
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; background:#fff; color:#111; margin:0; padding:40px; max-width: 860px; }
    h1 { font-size: 22px; margin-bottom: 2px; }
    h2 { font-size: 15px; margin-top: 34px; border-bottom: 1px solid #ddd; padding-bottom: 6px; }
    .muted { color: #666; font-size: 12px; }
    .small { font-size: 11px; }
    .score { font-size: 40px; font-weight: 700; }
    .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; margin: 14px 0; }
    .stat { border: 1px solid #e2e2e2; padding: 10px 12px; border-radius: 4px; }
    .stat .l { font-size: 10px; color: #777; text-transform: uppercase; letter-spacing: .03em; }
    .stat .v { font-size: 16px; font-family: monospace; margin-top: 3px; }
    table { border-collapse: collapse; width: 100%; font-size: 12px; margin-top: 8px; }
    td, th { border-bottom: 1px solid #eee; padding: 5px 8px; text-align: left; }
    .finding { border: 1px solid #e2e2e2; border-radius: 4px; padding: 12px 14px; margin: 10px 0; page-break-inside: avoid; }
    .finding-head { display:flex; align-items:center; gap:8px; margin-bottom:2px; }
    .pill { font-size: 10px; font-family: monospace; padding: 1px 6px; border-radius: 3px; border: 1px solid #999; }
    .sev-high .pill { color: #b3261e; border-color: #b3261e; }
    .sev-medium .pill { color: #8a5b00; border-color: #8a5b00; }
    .sev-low .pill { color: #2a5db0; border-color: #2a5db0; }
    .finding-body { margin-top: 8px; font-size: 12.5px; }
    .label { font-size: 10px; text-transform: uppercase; color: #888; letter-spacing: .03em; }
    ul { margin: 3px 0 8px 18px; padding: 0; }
    .disclaimer { font-size: 10.5px; color: #888; margin-top: 30px; border-top: 1px solid #eee; padding-top: 10px; }
    @media print { body { padding: 20px; } }
    """

    body = f"""
    <h1>Rawform — Mix Analysis Report</h1>
    <div class="muted">{_esc(m['filename'])} &middot; {_esc(genre['display_name'])} / {_esc(genre['subprofile_label'])} &middot; generated by Rawform v{_esc(result.get('engine_version'))}</div>

    <div class="grid" style="margin-top:20px;">
      <div class="stat"><div class="l">Mix Health</div><div class="score">{mh['overall_score'] if mh['overall_score'] is not None else '—'}<span style="font-size:16px;color:#999;">/100</span></div></div>
      <div class="stat"><div class="l">Duration</div><div class="v">{m['duration_seconds']:.1f}s</div></div>
      <div class="stat"><div class="l">BPM</div><div class="v">{m['bpm'] if m['bpm'] else 'Not confidently detected'}</div></div>
      <div class="stat"><div class="l">Key</div><div class="v">{m['key'] if m['key'] else 'Not confidently detected'}</div></div>
    </div>

    <h2>Track Information</h2>
    <div class="grid">
      <div class="stat"><div class="l">Sample Rate</div><div class="v">{m['sample_rate']} Hz</div></div>
      <div class="stat"><div class="l">Bit Depth</div><div class="v">{m['bit_depth'] or '—'}-bit</div></div>
      <div class="stat"><div class="l">Channels</div><div class="v">{'Stereo' if m['channels']==2 else 'Mono'}</div></div>
      <div class="stat"><div class="l">Format</div><div class="v">{_esc(m['format']).upper()}</div></div>
    </div>

    <h2>Loudness</h2>
    <div class="grid">
      <div class="stat"><div class="l">Integrated LUFS</div><div class="v">{lo['integrated_lufs'] if lo['integrated_lufs'] is not None else '—'}</div></div>
      <div class="stat"><div class="l">True Peak</div><div class="v">{lo['true_peak_dbtp']} dBTP</div></div>
      <div class="stat"><div class="l">Loudness Range</div><div class="v">{lo['loudness_range_lu'] if lo['loudness_range_lu'] is not None else '—'} LU</div></div>
      <div class="stat"><div class="l">RMS</div><div class="v">{lo['rms_dbfs']} dBFS</div></div>
    </div>

    <h2>Dynamics</h2>
    <div class="grid">
      <div class="stat"><div class="l">Crest Factor</div><div class="v">{dy['crest_factor_db']} dB</div></div>
      <div class="stat"><div class="l">Dynamic Variation</div><div class="v">{dy['dynamic_variation_db']} dB</div></div>
    </div>

    <h2>Low End</h2>
    <div class="grid">
      <div class="stat"><div class="l">Sub (20-40Hz)</div><div class="v">{(le['sub_energy_relative'] or 0)*100:.1f}%</div></div>
      <div class="stat"><div class="l">Bass (40-120Hz)</div><div class="v">{(le['bass_energy_relative'] or 0)*100:.1f}%</div></div>
      <div class="stat"><div class="l">Low-Mid (120-300Hz)</div><div class="v">{(le['low_mid_energy_relative'] or 0)*100:.1f}%</div></div>
      <div class="stat"><div class="l">Mono Compatible</div><div class="v">{'Yes' if le['low_frequency_mono_compatible'] else 'Check' if le['low_frequency_mono_compatible'] is False else '—'}</div></div>
    </div>
    <table><tr><th>Band</th><th>Energy</th><th>Relative</th></tr>{_band_rows(le['bands'])}</table>

    <h2>Kick / Bass</h2>
    <div class="grid">
      <div class="stat"><div class="l">Kicks Detected</div><div class="v">{kb['kick_count']}</div></div>
      <div class="stat"><div class="l">Detection Confidence</div><div class="v">{round(kb['kick_detection_confidence']*100)}%</div></div>
      <div class="stat"><div class="l">Kick Fundamental</div><div class="v">{kb['kick_fundamental_hz_median'] or '—'} Hz</div></div>
      <div class="stat"><div class="l">Overlap Events</div><div class="v">{len(kb['kick_bass_overlap_events'])}</div></div>
    </div>

    <h2>Stereo &amp; Mono Compatibility</h2>
    <div class="grid">
      <div class="stat"><div class="l">Phase Correlation</div><div class="v">{st['phase_correlation'] if st['phase_correlation'] is not None else '—'}</div></div>
      <div class="stat"><div class="l">Side/Mid Ratio</div><div class="v">{st['side_to_mid_ratio_db']} dB</div></div>
      <div class="stat"><div class="l">Mono Compatible</div><div class="v">{'Yes' if st['mono_compatible'] else 'Check' if st['mono_compatible'] is False else '—'}</div></div>
    </div>

    <h2>Clipping</h2>
    <p class="small">{'Digital clipping detected: ' + str(cl['clipped_sample_count']) + ' samples across ' + str(len(cl['clipping_events'])) + ' event(s).' if cl['clipping_detected'] else 'No digital clipping detected.'}</p>

    <h2>Findings &amp; Recommendations ({len(result['findings'])})</h2>
    {_findings_html(result['findings'])}

    <div class="disclaimer">
      {'<br/>'.join(_esc(d) for d in result.get('disclaimers', []))}
      <br/>This is a technical diagnostic report, not an objective judgment of musical quality. Generated by Rawform — audio was analyzed by your own Rawform backend, not a third-party service.
    </div>
    """

    return f"<!DOCTYPE html><html><head><meta charset='utf-8'><title>Rawform Report — {_esc(m['filename'])}</title><style>{css}</style></head><body>{body}</body></html>"
